language: c

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libc6-dbg wget git

install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - export MINICONDA=$HOME/miniconda
  - bash miniconda.sh -b -p $HOME/miniconda
  - hash -r
  - source $MINICONDA/etc/profile.d/conda.sh
  - conda config --set always_yes yes --set changeps1 no
  - conda update --quiet --yes conda
  - conda info -a
  - conda env create --quiet --name umem-dev --file .conda/environment.yml
  - conda activate umem-dev
  - export PREFIX=$CONDA_PREFIX

before_script:
  - mkdir build-umem-c
  - cd build-umem-c
  - cmake ../c
  - make -j4

script:
  - make test
  - ctest -D ExperimentalMemCheck -E test_cuda
  - head -n 50 Testing/Temporary/MemoryChecker.*.log
