version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Set up environment variables
          command: |
            echo 'export MINICONDA=$HOME/miniconda' >> $BASH_ENV
            #echo 'export PATH=$MINICONDA/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
            env
      - run:
          name: Update
          command: |
            apt-get update --assume-yes
            apt-get install --assume-yes wget git bzip2
            which wget
      - checkout
      - run:
          name: Install miniconda
          command: |
            cd $HOME
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
            bash miniconda.sh -b -f -p $MINICONDA
            conda config --set always_yes yes
            conda update conda
            conda config --add channels conda-forge
            conda info -a
            conda create -n testenv
            source activate testenv
      - run:
          name: Current working directory and listing
          command: echo "`pwd`:\n `ls -la`"
