version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Update
          command: |
            apt-get update --assume-yes
            apt-get install --assume-yes wget git
            which wget
      - checkout
      - run:
          name: Environment
          command: env
      - run:
          name: Install miniconda
          environment:
            MINICONDA: $HOME/miniconda
            PATH: $MINICONDA/bin:$PATH
          command: |
            cd $HOME
            env
            hash -r
            env
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
            bash miniconda.sh -b -f -p $MINICONDA
            conda config --set always_yes yes
            conda update conda
            conda config --add channels conda-forge
            conda info -a
            conda create -n testenv
            conda activate testenv
      - run:
          name: Current working directory and listing
          command: echo "`pwd`:\n `ls -la`"
