package:
  name: libumem
  version: 0.0.1.dev1

source:
  git_url: ../


build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: {{ environ.get('GIT_BUILD_STR', 'NA') }}

test:
  skip: True  # tests are in build.sh

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - valgrind
  host:
  run:


about:
  home: https://github.com/plures/umem
  license: BSD 3-clause